# Generated by Django 4.0 on 2022-04-02 20:55

from django.db import migrations, models
import vat_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('vat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateField(validators=[vat_app.models.is_valid_date]),
        ),
    ]
