# Generated by Django 4.0 on 2022-04-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vat_app', '0002_alter_transaction_trans_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateField(),
        ),
    ]
