# Generated by Django 4.0 on 2022-04-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vat_app', '0003_alter_transaction_trans_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(),
        ),
    ]
